### ISSUE TITLE
feature request addr:street and addr:housenumber points

### ISSUE THREAD

**Issue by marcobra** [Zverik/qgis_wp#10]
hi Zverik, thank for this useful plugin, i'm trying to use your work to improve detail and to catch errors in osm map looking for addr:housenumber details, i' have changed some settings in point section of osmconf.ini 

report_all_nodes=yes
...
attributes=name,barrier,highway,ref,address,is_in,place,man_made,addr:housenumber,addr:street

but i have no success to get them in map.
Do you have some tips ?

best regards and  thanks
marco

**Comment by Zverik** [comment]
You would also need to adjust `wp_style.yaml` in the same directory, to display points with these tags. I assume the layer would be `points`, query `add_housenumber not null`.

**Comment by marcobra** [comment]
I've add in  ~/.qgis2/python/plugins/walking_papers/res/wp_style.yaml

```
    name: Addresses
    layer: points
    query: addr_housenumber not null
    style:
        fill:
            color: "#fafafa"
            line-color: "#777777"
            line-width: 0.3
        label:
            field: addr_housenumber
            color: "#aaaaaa"
            font-size: 8
            buffer-size: 1
            text-align: center
            line-height: 0.6
```
and i modified the row below in  ~/.qgis2/python/plugins/walking_papers/res/osmconf.ini

```
# keys to report as OGR fields
attributes=name,barrier,highway,ref,address,is_in,place,man_made,addr:housenumber,addr:street
```

![photo_2017-07-06_21-58-15](https://user-images.githubusercontent.com/1607387/27930465-f52a367c-6296-11e7-9503-c24bdf17d1bd.jpg)
thank
Marco
